# Generated by Django 5.1.1 on 2024-12-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MenuAPI", "0002_category_menu_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="category",
        ),
    ]
