# Generated by Django 5.1.1 on 2024-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MenuAPI", "0005_alter_menu_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(default=1),
        ),
    ]
