# Generated by Django 5.1.1 on 2024-12-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0002_category_remove_menuitem_inventory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonDRF.category",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
