# Generated by Django 5.1.1 on 2024-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
