# Generated by Django 5.1.1 on 2024-12-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
