# Generated by Django 5.1.1 on 2024-11-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="Users",
        ),
    ]
