# Generated by Django 5.1.1 on 2024-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0003_rename_user_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Use",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
