# Generated by Django 5.1.1 on 2024-11-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0004_use_delete_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Use",
            new_name="User",
        ),
    ]
