# Generated by Django 5.1.1 on 2024-11-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0006_department_user_dept_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                ("strength", models.IntegerField(auto_created=True)),
                ("CollegeID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("TeacherID", models.IntegerField(primary_key=True, serialize=False)),
                ("Qualification", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="joined_date",
            field=models.DateTimeField(default="2020-04-01"),
        ),
        migrations.AddField(
            model_name="user",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Qualification", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                (
                    "CollegeID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demoapp.college",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("Subjectcode", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("credits", models.IntegerField()),
                ("teacher", models.ManyToManyField(to="demoapp.teacher")),
            ],
        ),
    ]
