# Generated by Django 5.1.1 on 2024-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0007_college_teacher_user_joined_date_user_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(help_text="college mail", max_length=254)),
                ("password", models.CharField(max_length=200)),
                ("passout_year", models.IntegerField()),
                ("about", models.CharField(max_length=200)),
                ("available_on", models.DateField()),
                (
                    "applying_to",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Tester", "Tester"),
                            ("DevOps engineer", "DevOps engineer"),
                        ],
                        max_length=200,
                    ),
                ),
                ("resume", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="principal",
            name="CollegeID",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dept_id",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="College",
        ),
        migrations.DeleteModel(
            name="Principal",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
