# Generated by Django 5.1.1 on 2024-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0008_application_remove_principal_collegeid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(
                help_text="college mail", max_length=254, unique=True
            ),
        ),
    ]
