# Generated by Django 5.1.1 on 2024-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0009_alter_application_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="available_on",
            field=models.DateTimeField(),
        ),
    ]
