# Generated by Django 5.1.1 on 2024-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0010_alter_application_available_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="available_on",
            field=models.DateField(),
        ),
    ]
