# Generated by Django 5.1.1 on 2024-11-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0011_alter_application_available_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "permissions": [("can_change_applyng_to", "Can change applying to")]
            },
        ),
    ]
