# Generated by Django 5.1.1 on 2024-11-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0012_alter_application_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"permissions": [("can_change_resume", "Can change resume")]},
        ),
    ]
