# Generated by Django 5.1.1 on 2024-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0014_alter_application_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=150)),
                ("booking_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
